### PR TITLE
Update Readme to include all category

### PR DESCRIPTION
**Pull request by mmrabbani**
## Description

Please provide a clear and concise description of your pull request, including:
- The changes made
- The reason for the changes
- Any relevant background information

## Related Issues

Please link any related issues that your pull request addresses or closes.

## Checklist

- [ ] I have read and followed the [contributing guidelines](/CONTRIBUTING.md).
- [ ] I have tested my changes.
- [ ] I have updated the documentation, if necessary.

## Additional Information

Any additional information you would like to provide.

### CODE REVIEW

**Comment by bootmortis** [comment]
مرسی
اگر ممکنه داک فارسی هم اپدیت کنید که با هم مرج بشه

**Comment by mmrabbani** [comment]
داکیومنت فارسی را هم اصلاح کردم. فقط تا جایی که فهمیدم شرایط برای clash فرق داره و در نتیجه اون بخش رو دست نزدم

**Comment by bootmortis** [comment]
ممنون

**Comment by bootmortis** [comment]
Related #134

**Pull request merged**
