### PR TITLE
delete some custom domains that are already in Enamad and ito-gov list

### PR DESCRIPTION
**Pull request by mmrabbani**
I compared custom domain list with Enamad list.
reducing the size can improve maintainability

### CODE REVIEW

**Comment by mmrabbani** [comment]
I also compared the list with ito-gov-mirror and deleted some other domains.

**Comment by bootmortis** [comment]
Thank you! This is something I have always wanted to do.

**Comment by bootmortis** [comment]
If you have time, please check the [v2fly ](https://github.com/v2fly/domain-list-community) and [iwmf ](https://github.com/Chocolate4U/iwmf.ir-Mirror) sources and open another PR.

**Comment by mmrabbani** [comment]
I can check iwmf.
Which part of v2fly do you mean? It has more than 1000 lists.

**Comment by bootmortis** [comment]
> I can check iwmf.
Thanks!

> I can check iwmf. Which part of v2fly do you mean? It has more than 1000 lists.

All `-ir` files of v2flay are added in this repo.
image

**Pull request merged**
