### PR TITLE
Bundle screenshots and fix image layout

### PR DESCRIPTION
**Pull request by Azadzadeh**
Some formatting changes.

### CODE REVIEW

**Review by bootmortis — COMMENTED** [review]
Thank you for your participation.
Can you also reduce the size of the screenshots so that each photo takes up less than 50KB? It is better to be around 20KB if possible.

**Comment by Azadzadeh** [comment]
from ~400KB to ~150KB

**Review by bootmortis — APPROVED** [review]
That's great.

**Comment by bootmortis** [comment]
@Azadzadeh I didn't notice that formats are changed from `.png` to `.jpg`  
If you have time, could you please open another pr and change them to `.png` with transparent bg?

**Pull request merged**
